### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/grit_output.txt'

### ISSUE THREAD

**Issue by tensorboy** [showlab/Image2Paragraph#1]
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/grit_output.txt'

**Comment by FingerRec** [comment]
Hi tensorboy:

Thanks for your question.

This file is generated by utils/image_dense_captions.py in GRiT.

I update this script and you can find this txt file now
