### ISSUE TITLE
pydantic

### ISSUE THREAD

**Issue by cloverGithub** [showlab/Image2Paragraph#30]
in pydantic.fields.ModelField._type_analysis:550  
TypeError: issubclass() arg 1 must be a class

Anyone with this issue, can advise how to resolve?

**Comment by ee2110** [comment]
Hi @cloverGithub , I have also encountered same issue when I try to run on new machine, but I can use the tool before this in another machine, could you help to advise how do you solve this error? thank you

**Comment by cloverGithub** [comment]
Hi, as it has been a while, i can't fully remember how i fixed it. 
I think i followed https://github.com/pydantic/pydantic/issues/545 , i.e. fix the type_extensions package.
Hope this helps. Thanks.
