### ISSUE TITLE
Does anyone want to help on getting a notebook or huggingface space version of this repo?

### ISSUE THREAD

**Issue by brianjking** [showlab/Image2Paragraph#4]
I'm starting but I would love some help, especially from someone with more talent 😂

**Comment by FingerRec** [comment]
hi brianiking,

Thanks for your effort.

The dependencies of GRIT is a little complicated, but I will try to incorporate all models into single notebook file recent days.

If you finish it, I'm also willing to merge it.

**Comment by FingerRec** [comment]
The HuggingFace space is online now. 

https://huggingface.co/spaces/Awiny/Image2Paragraph

As GPU is expensive, we give CPU demo.
