### ISSUE TITLE
Dense Caption always return empty

### ISSUE THREAD

**Issue by mickelliu** [showlab/Image2Paragraph#6]
Hi,

Thanks for sharing this work. Very interesting and potentially very impactful.

I encounter this issue while running `python main.py --image_src "/Code/Image2Paragraph/examples/3.jpg" --out_image_name "output/3_result.jpg"
`

"Dense Cpation" always returns "/", and the program processes without error. I was able to get the generated text at the end along with the style-transferred image, but the caption is a bit off potentially due to the missing dense caption.

![1](https://user-images.githubusercontent.com/20177526/232002897-64e51d91-b1ef-48cf-900f-68d66e7bb8d5.png)

**Comment by FingerRec** [comment]
hi mickeliu:

Since the dependencies of GRIT is complex so I call a subprocess to call the GRIT model.

As GRIT will output a log of logs, I keep 'quiet' for this model feedback.

To solve this, check you can run GRIT demo independently successfully, then check the env name in GRIT_model.py.

**Comment by FingerRec** [comment]
hi, we have integrated the grit into our code, no need to install grit independently anymore, follow install.md for details.

**Comment by mickelliu** [comment]
> hi, we have integrated the grit into our code, no need to install grit independently anymore, follow install.md for details.

Thanks for letting me know and thanks for the hard work. I will check it out later.
